CREATE USER IF NOT EXISTS 'db-migrator'@'%' IDENTIFIED BY 'db-migrator';
CREATE USER IF NOT EXISTS 'mysql'@'%' IDENTIFIED BY 'password';

CREATE DATABASE IF NOT EXISTS `mydb`;

REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'db-migrator'@'%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'mysql'@'%';

GRANT ALL PRIVILEGES ON *.* TO 'db-migrator'@'%' WITH GRANT OPTION;
GRANT CREATE USER ON *.* TO 'db-migrator'@'%' WITH GRANT OPTION;
GRANT SELECT ON mysql.* TO 'db-migrator'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON `mydb`.* TO 'mysql'@'%';

CREATE USER IF NOT EXISTS 'test-user'@'%' IDENTIFIED BY 'test-password';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'test-user'@'%';

CREATE DATABASE IF NOT EXISTS `test_db`;
GRANT ALL PRIVILEGES ON `test_db`.* TO 'test-user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
